monitor = int(input("Enter cost of monitor = "))
sUnit = int(input("Enter cost of system unit = "))
kBoard = int(input("Enter cost of keyboard = "))
comMouse = int(input("Enter cost of computer mouse = "))
print("\nCost of 3 computers = ", 3 * (monitor + sUnit + kBoard + comMouse))
n = int(input("Enter the number of computers you are interested in: "))
print("\nCost of", n, "computers = ", n * (monitor + sUnit + kBoard + comMouse))
